language: python
python:
  - "3.7"
env:
  - SPHINX_VERSION=dev
  - SPHINX_VERSION=2.1.0
  - SPHINX_VERSION=2.0.0
  - SPHINX_VERSION=1.8
matrix:
  include:
    - python: "3.6"
      env: SPHINX_VERSION=dev
    - python: "3.5"
      env: SPHINX_VERSION=1.8.0
    - python: "3.5"
      env: SPHINX_VERSION=1.7.0
    - python: "3.5"
      env: SPHINX_VERSION=1.6.0
    - python: "3.5"
      env: SPHINX_VERSION=1.5.0
    - python: "3.5"
      env: SPHINX_VERSION=1.4.0
    - python: "3.5"
      env: SPHINX_VERSION=1.3.0
    - python: "3.5"
      env: SPHINX_VERSION=1.2.0
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -e .
  - |
    if [ $SPHINX_VERSION = dev ] ; then
        pip install https://github.com/sphinx-doc/sphinx/archive/master.zip
    else
        pip install Sphinx~=$SPHINX_VERSION
    fi
script:
  - pytest .
